"""add role id

迁移 ID: 8e37a3c71942
父迁移: 220f4e0d01fd
创建时间: 2026-02-25 17:21:53.912006

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8e37a3c71942"
down_revision: str | Sequence[str] | None = "220f4e0d01fd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skland_characters", schema=None) as batch_op:
        batch_op.add_column(sa.Column("role_id", sa.VARCHAR(), nullable=True, comment="角色ID"))

    # 对于终末地角色，将之前存储在 uid 中的 roleId 复制到 role_id 字段
    # 迁移后需手动执行「全体角色更新」以修正 uid 为正确值
    characters_table = sa.table(
        "skland_characters",
        sa.column("uid", sa.Text),
        sa.column("role_id", sa.VARCHAR),
        sa.column("app_code", sa.Text),
    )
    op.execute(
        characters_table.update()
        .where(characters_table.c.app_code == "endfield")
        .values(role_id=characters_table.c.uid)
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skland_characters", schema=None) as batch_op:
        batch_op.drop_column("role_id")

    # ### end Alembic commands ###
