"""ef gacha support

迁移 ID: a689da19471b
父迁移: 8e37a3c71942
创建时间: 2026-02-28 13:19:39.025960

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a689da19471b"
down_revision: str | Sequence[str] | None = "8e37a3c71942"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skland_gacha_record", schema=None) as batch_op:
        batch_op.add_column(sa.Column("app_code", sa.Text(), server_default="arknights", nullable=False))
        batch_op.add_column(sa.Column("item_type", sa.Text(), server_default="char", nullable=False))
        batch_op.add_column(sa.Column("is_free", sa.Boolean(), server_default="0", nullable=False))
        batch_op.drop_constraint("_character_ts_pos_uc", type_="unique")
        batch_op.create_unique_constraint("_app_char_ts_pos_uc", ["char_uid", "app_code", "gacha_ts", "pos"])
        batch_op.create_index(batch_op.f("ix_skland_gacha_record_app_code"), ["app_code"], unique=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skland_gacha_record", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skland_gacha_record_app_code"))
        batch_op.drop_constraint("_app_char_ts_pos_uc", type_="unique")
        batch_op.create_unique_constraint("_character_ts_pos_uc", ["char_id", "gacha_ts", "pos"])
        batch_op.drop_column("is_free")
        batch_op.drop_column("item_type")
        batch_op.drop_column("app_code")

    # ### end Alembic commands ###
